### ISSUE TITLE
Request for Paper

### ISSUE THREAD

**Issue by ItamarEliakim-R** [open-rmf/rmf_reservation#7]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

Hey,

Awesome job on the project! I'm really looking forward to trying it out in real-world situations.

Any chance you could share a link to the paper if it's online? I'd love to read more about it.

Thanks a lot!
Itamar

**Comment by ItamarEliakim-R** [comment]
@arjo129

**Comment by arjo129** [comment]
Hi @ItamarEliakim-R , I'll look into uploading the paper to arxiv or some other place.

**Comment by arjo129** [comment]
Done here: https://arxiv.org/abs/2408.07942

**Comment by ItamarEliakim-R** [comment]
Awesome work guys! I'll look into it. Thanks a lot.

**Comment by arjo129** [comment]
Thanks! Its early days for this library. I would say its at "research level" (don't use in production) a lot of work is left to get this useable. Including integrating with `bevy_impulse`. Expect bugs.

**Comment by ItamarEliakim-R** [comment]
Yep. Thanks @arjo129!
I am aware of that and would love to contribute back to features later in these areas.
I'll dive deeper into it soon, so I can provide more feedback.
